mode:
    production

production:
    datasources:
        mysql:
            disable: true
        mongodb:
           disable: true
        redis:
           disable: true

application:
    controllerNames: mammuthus.deploy.dynamic.controller.slave.DynamicSlaveController
    static:
           enable: true
    template:
        engine:
           enable: false

###############http config##################
http:
    disable: false
    class:
        port: mammuthus.deploy.dynamic.service.slave.RandomPortGenerator
thrift:
    disable: true
dubbo:
    disable: true
